name: Generating Changelog File

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Generate Changelog
              uses: mikepenz/release-changelog-builder-action@v1.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  configuration: ".github/configuration_file.json"

            - name: Commit Changelog
              run: |
                  git config --global user.name "GitHub Action"
                  git config --global user.email "actions@github.com"
                  git add CHANGELOG.md || echo "No changes in CHANGELOG.md"
                  git diff --staged --quiet || git commit -m "chore(release): update CHANGELOG.md [skip ci]" -m "[skip ci]"
                  git push origin HEAD:main
