name: Build and Release Project

on:
    push:
        branches:
            - main

    workflow_dispatch: {}

jobs:
    activation:
        name: Acquire Unity License
        runs-on: ubuntu-latest
        outputs:
            unity_license: ${{ steps.ulfRead.outputs.content }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup a Node.JS environment
              uses: actions/setup-node@v2
              with:
                  node-version: "18.0.0"

            - name: Install node package `unity-license-activate`
              run: npm install -g unity-license-activate

            - name: Activate Unity License
              run: |
                  unity-license-activate "${{ secrets.UNITY_EMAIL }}" "${{ secrets.UNITY_PASSWORD }}"
              env:
                  UNITY_LICENSE_FILE: ${{ github.workspace}}/Unity_lic.ulf

            - name: Read Unity License File
              id: ulfRead
              uses: juliangruber/read-file-action@v1.1.4
              with:
                  path: ${{ github.workspace}}/Unity_lic.ulf

            - name: Upload Unity License File
              uses: actions/upload-artifact@v2
              with:
                  name: Unity License File
                  path: ${{ github.workspace}}/Unity_lic.ulf
